version: "3"

services:
  dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        links:
             - mongodb
        restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    environment:
      - MONGODB_DATABASE="weather"
    ports:
      - 27017:27017